### PR TITLE
dont send ReadyForQuery after error response

### PR DESCRIPTION
**Pull request by poudels14**
- the server needs to wait for Sync message from the frontend
  before it sends ready for query message back to frontend
- read and discard messages until a Sync is received

### CODE REVIEW

**Comment by sunng87** [comment]
This is a lint issue that we need to remove unused imports.

**Comment by poudels14** [comment]
Fixed the lint issue. Also made additional changes to read and discard messages from the socket until the Sync message is received. That behavior is documented in the postgres docs: https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY

**Comment by sunng87** [comment]
Thank you @poudels14

**Comment by sunng87** [comment]
@poudels14 I'm running into an issue that `psql` hangs when error occurs. I investigated simple query message flow and the server actually sends `ReadForQuery` after error.

image

**Comment by sunng87** [comment]
I just created #148 to fix that.

**Pull request merged**
